# Assignment For Numpy

# Difficulty Level Beginner

In [2]:
import numpy as np

In [5]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
x=np.arange(10,49)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [7]:
x=np.arange(10,49)
np.shape(x)

(39,)

In [9]:
x.dtype

dtype('int64')

In [13]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [14]:
x.ndim

1

In [18]:
y=np.ones((2, 2), dtype=bool)
y

array([[ True,  True],
       [ True,  True]])

In [23]:
a=np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
b=np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Difficulty Level Easy

In [27]:
c = np.arange(1, 11)
print("Original array:")
print(c)
print("Reverse array:")
c = c[::-1]
print(c)

Original array:
[ 1  2  3  4  5  6  7  8  9 10]
Reverse array:
[10  9  8  7  6  5  4  3  2  1]


In [30]:
d = np.zeros(10)
print(d)
print("Update fifth value to 1")
d[5] = 1
print(d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [31]:
e=np.ones((3,3))
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr = np.array([1, 2, 3, 4, 5],dtype=float)
arr.dtype

dtype('float64')

In [33]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [35]:
arr3=arr1[arr2>arr1]
arr3

array([2., 4., 6.])

In [49]:
f=np.arange(0,9)
f
d=f[f%2!=0]
d

array([1, 3, 5, 7])

In [89]:
g=np.where(f%2!=0,-1,f*1)
g

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

In [92]:
arr = np.arange(10)
q=np.where(arr>4,np.where(arr<9,12,arr*1),arr*1)
q

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [102]:
r=np.ones((5,5))
r[1:-1,1:-1]=0
r

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Difficulty Level Medium

In [103]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [135]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0:1,0:-1]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [150]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d=arr2d[0,0:3]
arr2d

array([1, 2, 3])

In [151]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d=arr2d[1,1:3]
arr2d

array([5, 6])

In [153]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.38629471 0.21426171 0.46873274 0.44422763 0.99721239 0.90653344
  0.18973576 0.71193773 0.99370262 0.02721463]
 [0.73865755 0.30910404 0.77960875 0.39922943 0.8054144  0.17910769
  0.64264093 0.56813007 0.95921515 0.09733277]
 [0.40863994 0.98919154 0.34649206 0.05332709 0.0561928  0.09360678
  0.99828119 0.28969796 0.52614194 0.16242692]
 [0.20587375 0.46650343 0.151317   0.45034839 0.03505558 0.24798304
  0.44802509 0.43180403 0.64713215 0.11409874]
 [0.25022744 0.59440591 0.22046357 0.85578048 0.56318919 0.67329823
  0.46892848 0.4403589  0.68221052 0.95830111]
 [0.67886892 0.92094787 0.13701232 0.74459084 0.06214242 0.18442956
  0.22515204 0.50865778 0.95879977 0.31631781]
 [0.07850778 0.41182088 0.66608108 0.93161486 0.24669783 0.2125997
  0.09342057 0.05527334 0.55769219 0.32989631]
 [0.71527131 0.08341883 0.32059812 0.83151647 0.64618325 0.16755737
  0.88806205 0.67977959 0.39474736 0.96189258]
 [0.04310426 0.10786547 0.43746904 0.6349826  0.20488339 0.506956

In [155]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b)) 

[2 4]


In [156]:
np.where(np.in1d(a, b))[0]

array([1, 3, 5, 7])

In [157]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
hello=data[names != 'Will']
hello

array([[ 0.85395631,  2.14738196, -0.64273662,  0.8486707 ],
       [ 0.22710404, -0.95032434,  1.34510684,  0.1202851 ],
       [-1.0798093 , -2.58714078,  0.52315817,  0.11565988],
       [-0.75556312,  0.20578862,  0.67768911,  1.51420652],
       [ 0.43782287,  0.07556168, -0.01192665,  0.33884345]])

In [161]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
hello=(names == 'Bob') | (names == 'Will')
data[hello]

array([[-0.35180258, -0.56842621,  0.35840166,  2.07369247],
       [ 0.34249727,  0.38635918,  1.51291516, -0.12752193],
       [-0.40503927,  0.90998538, -1.22408943, -0.32491565],
       [ 1.37928743,  0.37043597, -0.85779523, -1.0717335 ]])

# Difficulty Level Hard

In [162]:
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[8.88465333, 9.10540226, 6.29339881],
       [5.42184223, 8.22856476, 7.15208859],
       [9.71162432, 8.81857977, 8.10028873],
       [9.16256717, 6.4518511 , 6.82354852],
       [9.53336388, 9.04837325, 7.92181198]])

In [165]:
arr = np.random.uniform(1,16, size=(2,2,4))
arr

array([[[11.31071934,  5.77005113, 15.89885866, 10.08734027],
        [ 1.83030964, 14.15790786, 12.33986425,  1.40937308]],

       [[12.33838888, 10.34624471,  3.08472404,  8.1604064 ],
        [ 2.88445444,  7.81000352,  7.57186746,  6.60138073]]])

In [166]:
np.swapaxes(arr,0,1)

array([[[11.31071934,  5.77005113, 15.89885866, 10.08734027],
        [12.33838888, 10.34624471,  3.08472404,  8.1604064 ]],

       [[ 1.83030964, 14.15790786, 12.33986425,  1.40937308],
        [ 2.88445444,  7.81000352,  7.57186746,  6.60138073]]])

In [170]:
ar=np.arange(10)
print(ar)
a=np.sqrt(ar)
print(a)
b=np.where(a<0.5,0,a*1)
b

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [16]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
arr=np.concatenate((a1,a2),axis=0)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
h=np.unique(names)
h

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [19]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])
print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [21]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [22]:
l=np.random.randn(20)
x=np.cumsum(l)
x

array([-0.19344132, -0.28181461, -1.29756287, -1.77671251, -3.45493732,
       -1.82886202, -0.64347193, -0.5440207 , -0.11535013, -0.64974352,
       -0.28375716,  2.35600801,  3.5530223 ,  2.76543413,  2.43525816,
        2.17622709,  3.09534942,  3.02454594,  4.22536674,  5.13304338])